<?php
/**
 * Created by PhpStorm.
 * User: djomla
 * Date: 20.12.18.
 * Time: 16.35
 */

require_once('MainController.php');
require_once(dirname(__DIR__) . '/lib/DateHelper.php');
class Vacation extends MainController
{
    private $model = 'vacation';

    public function handlePost() {
        $data = $this->client->getJSonRequest();
        /** @var VacationModel $vacationModel */
        $vacationModel = $this->getModel($this->model);

        /** @var DateHelper $dateHelper */
        $dateHelper = new DateHelper();
        $dateFrom = new DateTime($data['date_from']);
        $dateTo   = new DateTime($data['date_to']);
        $numOfDays = $dateHelper->dayDiffWithoutWeekend($dateFrom->format('Y-m-d'), $dateTo->format('Y-m-d'));

        $saveData = array(
            'userId'       => (int)$data['user_id'],
            'dateFrom'     => $dateFrom->format('Y-m-d'),
            'dateTo'       => $dateTo->format('Y-m-d'),
            'numberOfDays' => $numOfDays,
            'approvalUser' => 1
        );

        $res = $vacationModel->save($saveData);
        $this->view->renderSuccess($res);
    }

    /**
     * Validate status and if user have ACE to approve / decline vacation request
     * @return bool
     */
    public function validatePut() {
        return parent::validatePut(); // TODO: Change the autogenerated stub
    }

    public function handleGet() {
        $data = $this->client->getJSonRequest();

        /** @var VacationModel $model */
        $model  = $this->getModel('vacation');
        $res    = $model->getUserRequests($data['id']);
        $this->view->renderJSONOutput($res);
    }

    public function handlePut() {
        $data = $this->client->getJSonRequest();
        $updateData = array(
            'id'     => $data['id'],
            'status' => $data['status']
        );
        /** @var VacationModel $model */
        $model  = $this->getModel('vacation');
        $res    = $model->updateStatus($updateData);

        //Update user vacation days
        if (!empty($res)) {
            $vacationRow  = $model->getById($data['id']);
            $numberOfDays = $vacationRow['number_of_days'];
            $userId       = $vacationRow['user_id'];

            /** @var UserModel $userModel */
            $userModel = $this->getModel('user');
            $res = $userModel->updateNumberOfDays($userId, $numberOfDays);
            $this->view->renderSuccess($res);
        }
        $this->view->renderError('Nothing happen bro!');
    }
}